### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by wpoosanguansit** [leoantony72/E-commerce-Api#1]
Hi Antony,

I came across your code and I am interested in collaborating.  Would that be something you might be interested in?  Is there a way that we can chat?  Thanks!

Watt P.

**Comment by leoantony72** [comment]
We can chat through Twitter 🙂

**Comment by wpoosanguansit** [comment]
Can it be through email or slack or discord?  Just happens that I don't do twitter at all.  Thanks!

**Comment by leoantony72** [comment]
Discord : Wizard#9020
